name: user_collections
description: "Feature to handle user-created collections locally"
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  drift: ^2.21.0
  next_database_service: ^1.0.0
  either: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0