name: next_app

packages:
  - next_app
  - features/**
  - shared/**

scripts:
  # you should install fzf command line tool to run this command
  build:runner:select:
    run: |
      selected_package=$(melos list --parsable | fzf --multi --prompt="Select packages to run build_runner: " --height=5%) &&
      for package in $selected_package; do
        melos exec --scope=$package --dir-exists="lib" --depends-on="build_runner" -- flutter pub run build_runner build --delete-conflicting-outputs;
      done
    description: Run build_runner interactively for selected packages.
  build:runner:
    run: |
      melos exec --dir-exists="lib" --depends-on="build_runner" -- flutter pub run build_runner build --delete-conflicting-outputs
    description: Run build_runner in all packages that depend on it.
  build:runner:watch:
    run: |
      melos exec --dir-exists="lib" --depends-on="build_runner" -- flutter pub run build_runner watch
    description: Run build_runner in watch mode for all packages.
  build:runner:clean:
    run: |
      melos exec --dir-exists="lib" --depends-on="build_runner" -- flutter pub run build_runner clean
    description: Clean build_runner cache in all packages.
  analyze:
    run: dart analyze .
    exec:
      concurrency: 7
  unit_test:
    run: melos exec --dir-exists="test" -- flutter test --no-pub --coverage
    description: Run all Flutter tests in this project.
  coverage:merge: >
    rm -f merged_coverage.lcov.info &&
    for package_dir in */; do
      coverage_file="${package_dir}coverage/lcov.info";
      abs_package_path="$(cd "$package_dir" && pwd)";
      if [ -f "$coverage_file" ]; then
        sed "s|SF:|SF:$abs_package_path/|g" "$coverage_file" >> merged_coverage.lcov.info;
      fi
    done &&
    genhtml merged_coverage.lcov.info -o coverage_html --ignore-errors source --prefix=/Users/thisisyusub/Self/next-app/
  test:coverage:open:
    run: |
      melos run unit_test &&
      melos run coverage:merge &&
      open coverage_html/index.html
    description: Run tests, merge coverage, and open HTML report.
  gen-l10n:
    run: |
      melos exec -c 1 -- \
        'if [ -f "l10n.yaml" ]; then flutter gen-l10n; fi'
    
