name: next_app

packages:
  - google_books_service
  - itunes_service
  - moviedb_service
  - next_app
  - rest_service
  - next_database_service
  - facades
  - testing_utils

scripts:
  analyze:
    run: dart analyze .
    exec:
      concurrency: 7
  unit_test:
    run: melos exec --dir-exists="test" -- flutter test --no-pub --coverage
    description: Run all Flutter tests in this project.
  coverage:merge: >
    rm -f merged_coverage.lcov.info &&
    for package_dir in */; do
      coverage_file="${package_dir}coverage/lcov.info";
      abs_package_path="$(cd "$package_dir" && pwd)";
      if [ -f "$coverage_file" ]; then
        sed "s|SF:|SF:$abs_package_path/|g" "$coverage_file" >> merged_coverage.lcov.info;
      fi
    done &&
    genhtml merged_coverage.lcov.info -o coverage_html --ignore-errors source --prefix=/Users/thisisyusub/Self/next-app/
  test:coverage:open:
    run: |
      melos run unit_test &&
      melos run coverage:merge &&
      open coverage_html/index.html
    description: Run tests, merge coverage, and open HTML report.
    
