name: next_app

packages:
  - google_books_service
  - itunes_service
  - moviedb_service
  - next_app
  - rest_service
  - next_database_service
  - facades

scripts:
  analyze:
    exec: dart analyze .