name: next
publish_to: none

environment:
  sdk: ^3.6.0
  
workspace:
  - features/books
  - features/itunes
  - features/movies
  - features/user_collections
  - shared/either
  - shared/next_database_service
  - shared/rest_service
  - shared/testing_utils
  - next_app
