name: next_app
description: "Next App to handle your lifestyle with best one you love"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  clock: 1.1.1
  logging: ^1.3.0
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  rest_service: ^1.0.0
  itunes: ^1.0.0
  books: ^1.0.0
  movies: ^1.0.0
  user_collections: ^1.0.0
  next_database_service: ^1.0.0
  either: ^1.0.0
  equatable: ^2.0.7
  go_router: ^14.6.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder: ^2.7.1
  build_runner: ^2.4.13

flutter:
  generate: true
  uses-material-design: true
  assets:
    - config.json