name: rest_service
description: "Shared Abstract RestService"
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path: 1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0