// Mocks generated by Mockito 5.4.4 from annotations
// in itunes/test/data/data_sources/album_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rest_service/src/rest_client.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUri_0 extends _i1.SmartFake implements Uri {
  _FakeUri_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestClient extends _i1.Mock implements _i2.RestClient {
  @override
  Uri get baseUri => (super.noSuchMethod(
        Invocation.getter(#baseUri),
        returnValue: _FakeUri_0(
          this,
          Invocation.getter(#baseUri),
        ),
        returnValueForMissingStub: _FakeUri_0(
          this,
          Invocation.getter(#baseUri),
        ),
      ) as Uri);

  @override
  _i3.Future<Map<String, dynamic>?> get(
    String? url, {
    Map<String, String>? headers,
    Map<String, String>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {
            #headers: headers,
            #queryParameters: queryParameters,
          },
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  Uri buildUri(
    String? path, {
    Map<String, String>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildUri,
          [path],
          {#queryParameters: queryParameters},
        ),
        returnValue: _FakeUri_0(
          this,
          Invocation.method(
            #buildUri,
            [path],
            {#queryParameters: queryParameters},
          ),
        ),
        returnValueForMissingStub: _FakeUri_0(
          this,
          Invocation.method(
            #buildUri,
            [path],
            {#queryParameters: queryParameters},
          ),
        ),
      ) as Uri);

  @override
  dynamic decodeBody(String? data) => super.noSuchMethod(
        Invocation.method(
          #decodeBody,
          [data],
        ),
        returnValueForMissingStub: null,
      );
}
