name: testing_utils
description: "Shared Utils for testing"
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.4.4
  rest_service: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13