name: next_database_service
description: "Shared database service for features to handle collections"
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.11.1
  drift_flutter: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.4.1
  build_runner: ^2.3.3